In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from wordfreq import zipf_frequency
import mysql.connector
from sqlalchemy import create_engine

# -----------------
# Connect to MySQL
# -----------------
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="pwd",
    database="movie"
)

# Use SQLAlchemy engine (preferred by pandas)
engine = create_engine("mysql+pymysql://root:Hemil%407647@localhost/movie")

# -----------------
# Load data with SQL
# -----------------
query = """
SELECT 
    ms.content_id,
    ms.title,
    GROUP_CONCAT(DISTINCT g.name) AS genres,
    ms.release_year AS year,
    ms.description,
    GROUP_CONCAT(DISTINCT CASE WHEN cm.role = 'Director' THEN cm.name END) AS director,
    GROUP_CONCAT(DISTINCT CASE WHEN cm.role = 'Actor' THEN cm.name END) AS cast
FROM movie_series ms
LEFT JOIN content_genre cg ON ms.content_id = cg.content_id
LEFT JOIN genre g ON cg.genre_id = g.genre_id
LEFT JOIN content_cast cc ON ms.content_id = cc.content_id
LEFT JOIN cast_member cm ON cc.cast_id = cm.cast_id
GROUP BY ms.content_id, ms.title, ms.release_year, ms.description;
"""
df = pd.read_sql(query, engine)

# -----------------
# Handle missing values
# -----------------
df['Genres'] = df['genres'].fillna('Unknown')
df['Director'] = df['director'].fillna('Unknown')
df['Cast'] = df['cast'].fillna('Unknown')
df['Description'] = df['description'].fillna('Unknown')

# Replace pipe with space in genres
df['Genres'] = df['Genres'].str.replace('|', ' ', regex=False)

# -----------------
# Text cleaning
# -----------------
# Title
df['Title_raw'] = df['title']
df['Title_clean'] = df['title'].apply(
    lambda x: re.sub(r'[^a-z0-9]', '', str(x).lower().replace(" ", ""))
)

# Director
df['Director_clean'] = df['Director'].apply(
    lambda x: re.sub(r'[^a-z0-9]', '', str(x).lower())
)

# Cast
def clean_cast(cast_str):
    if not isinstance(cast_str, str):
        return "unknown"
    actors = cast_str.split(",")[:3]  # limit to top 3
    cleaned = [re.sub(r'[^a-z0-9]', '', a.lower()) for a in actors]
    return " ".join(cleaned)

df['Cast_clean'] = df['Cast'].apply(clean_cast)

# Description
def clean_text(text):
    if not isinstance(text, str):
        return ""
    words = re.findall(r'\b[a-z]+\b', text.lower())
    return " ".join([w for w in words if zipf_frequency(w, 'en') > 1.5])

df['Description_clean'] = df['Description'].apply(clean_text)

# -----------------
# Combine features
# -----------------
df['combined_text_2'] = (
    df['Title_clean'] + ' ' +
    df['Genres'] + ' ' +
    df['Director_clean'] + ' ' +
    df['Cast_clean'] + ' ' +
    df['Description_clean']
)

# -----------------
# Vectorization
# -----------------
vectorizer2 = TfidfVectorizer(stop_words='english', max_features=5000)
tfidf_matrix_2 = vectorizer2.fit_transform(df['combined_text_2'])
cosine_sim_2 = cosine_similarity(tfidf_matrix_2, tfidf_matrix_2)

print("Data prepared and cosine similarity matrix built ✅")


Data prepared and cosine similarity matrix built ✅


In [33]:
def get_user_recommendations(user_id, n=5, history_limit=20):
    # Step 1: fetch watch history (parameterized query)
    watched = pd.read_sql(
        """
        SELECT content_id 
        FROM watch_history 
        WHERE user_id = %s 
        ORDER BY watch_date ASC
        LIMIT %s
        """,
        con=engine,
        params=(user_id, history_limit)  # ✅ tuple not list
    )
    
    # Step 2: handle no history
    if watched.empty:
        return f"❌ No watch history found for user {user_id}."
    
    # Step 3: find indices in main df
    input_ids = watched['content_id'].tolist()
    input_indices = df[df['content_id'].isin(input_ids)].index.tolist()
    if not input_indices:
        return f"❌ No matching content found in main dataset for user {user_id}."
    
    # Step 4: compute similarity
    sim_scores = np.zeros(len(df))
    for idx in input_indices:
        sim_scores += cosine_sim_2[idx]
    sim_scores /= len(input_indices)
    
    # Step 5: remove watched content
    sim_scores = [(i, s) for i, s in enumerate(sim_scores)
                  if df.iloc[i]['content_id'] not in input_ids]
    
    # Step 6: top-N
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[:n]
    top_indices = [i for i, _ in sim_scores]
    similarity_scores = [round(s, 3) for _, s in sim_scores]
    
    # Step 7: build output DataFrame
    recs = df[['content_id', 'Title_raw', 'Genres', 'Director', 'Cast']].iloc[top_indices].copy()
    recs['Similarity'] = similarity_scores
    return recs.reset_index(drop=True)


In [35]:
# Recommend top 5 unique movies for user_id=1
recommendations = get_user_recommendations(user_id=22, n=5)
print(recommendations)


   content_id          Title_raw                            Genres  \
0          53  Avengers: Endgame     Action,Adventure,Drama,Sci-Fi   
1          39       The Avengers  Action,Adventure,Sci-Fi,Thriller   
2          36           3 Idiots       Comedy,Drama,Family,Romance   
3          37          Inception  Action,Adventure,Sci-Fi,Thriller   
4          41       Interstellar   Adventure,Drama,Sci-Fi,Thriller   

            Director                                               Cast  \
0            Unknown  Anushka Shetty,Chris Evans,Robert Downey Jr.,S...   
1        Joss Whedon   Chris Evans,Robert Downey Jr.,Scarlett Johansson   
2    Rajkumar Hirani              Aamir Khan,Kareena Kapoor,R. Madhavan   
3  Christopher Nolan   Joseph Gordon-Levitt,Leonardo DiCaprio,Tom Hardy   
4  Christopher Nolan                  Anne Hathaway,Matthew McConaughey   

   Similarity  
0       0.074  
1       0.069  
2       0.054  
3       0.052  
4       0.048  


In [5]:
import joblib

model_data = {
    "cosine_sim": cosine_sim_2,
    "content_ids": df['content_id'].tolist()
}

joblib.dump(model_data, "cbf_model.joblib")
print("✅ Content-based model saved as cbf_model.joblib")


✅ Content-based model saved as cbf_model.joblib


This way your Flask API can:

Load cbf_model.joblib

Look up the indexes of watched content_ids

Use cosine_sim to find similar items

In [2]:
import joblib
model_data = joblib.load("recommendation_model.joblib")
print(type(model_data))
print(model_data)


<class 'numpy.ndarray'>
[[1.         0.07070687 0.         ... 0.13367492 0.04516202 0.06702978]
 [0.07070687 1.         0.02233624 ... 0.02332886 0.03808847 0.07614374]
 [0.         0.02233624 1.         ... 0.07333316 0.01891407 0.02117465]
 ...
 [0.13367492 0.02332886 0.07333316 ... 1.         0.09884725 0.02211565]
 [0.04516202 0.03808847 0.01891407 ... 0.09884725 1.         0.03610769]
 [0.06702978 0.07614374 0.02117465 ... 0.02211565 0.03610769 1.        ]]
